theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  events:
    index:
      options:
        image: true
        subtitle: true
        summary: true
  posts:
    index:
      layout: grid
  search:
    active: true
  logo:
    header: "/assets/images/typo.svg"
    footer: "/assets/images/icon.svg"