[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/publications/ressource/index.html"
to = "/publications/typologie/ressource/"

[[redirects]]
from = "/membres/index.html"
to = "/personnes/"

[[redirects]]
from = "/actualites/2024-08-15-lancement-1-1/index.html"
to = "/publications/2024-08-15-lancement-1-1/"

[[redirects]]
from = "/agenda/2024/06/index.html"
to = "/evenements/2024/06/"

[[redirects]]
from = "/lassociation/contact/index.html"
to = "/contact/"

[[redirects]]
from = "/publications/typologies/index.html"
to = "/publications/typologie/"

[[redirects]]
from = "/agenda/2024-10-16-defaites-vos-jeux-1-1/index.html"
to = "/agenda/2024/defaites-vos-jeux-1-1/"

[[redirects]]
from = "/publications/thematiques/democratie/index.html"
to = "/publications/thematique/democratie/"

[[redirects]]
from = "/membres/thomas-thibault/index.html"
to = "/personnes/thomas-thibault/"

[[redirects]]
from = "/actualites/2024-08-15-lancement-1/index.html"
to = "/publications/2024-08-15-lancement-1/"

[[redirects]]
from = "/membres/thomas-thibault/publications/index.html"
to = "/personnes/thomas-thibault/publications/"

[[redirects]]
from = "/actualites/2024-08-15-discours-de-thomas-thibault-nouvelle-mandature-le-mouton-numerique/index.html"
to = "/publications/2024-08-15-discours-de-thomas-thibault/"

[[redirects]]
from = "/agenda/2024/05/index.html"
to = "/evenements/2024/05/"

[[redirects]]
from = "/equipe/thomas-thibault/actualites/index.html"
to = "/personnes/thomas-thibault/publications/"

[[redirects]]
from = "/equipe/thomas-thibault/index.html"
to = "/personnes/thomas-thibault/"

[[redirects]]
from = "/equipe/index.html"
to = "/personnes/"

[[redirects]]
from = "/lassociation/membres/thomas-thibault/index.html"
to = "/personnes/thomas-thibault/"

[[redirects]]
from = "/adherez/index.html"
to = "/adherer/"

[[redirects]]
from = "/publications/thematiques/ecologie/index.html"
to = "/publications/thematique/ecologie/"

[[redirects]]
from = "/agenda/2024/08/index.html"
to = "/evenements/2024/08/"

[[redirects]]
from = "/agenda/2024/12/index.html"
to = "/evenements/2024/12/"

[[redirects]]
from = "/agenda/2024/02/index.html"
to = "/evenements/2024/02/"

[[redirects]]
from = "/agenda/2024-06-16-defaites-vos-jeux/index.html"
to = "/agenda/2024/defaites-vos-jeux/"

[[redirects]]
from = "/equipe/equipe-editoriale/index.html"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/agenda/2024/04/index.html"
to = "/evenements/2024/04/"

[[redirects]]
from = "/actualites/2024-03-22-lancement/index.html"
to = "/publications/2024-03-22-lancement/"

[[redirects]]
from = "/publications/typologies/ressource/index.html"
to = "/publications/typologie/ressource/"

[[redirects]]
from = "/agenda/2024/10/index.html"
to = "/evenements/2024/10/"

[[redirects]]
from = "/lassociation/membres/thomas-thibault/actualites/index.html"
to = "/personnes/thomas-thibault/publications/"

[[redirects]]
from = "/agenda/2024-09-16-defaites-vos-jeux-1/index.html"
to = "/agenda/2024/defaites-vos-jeux-1/"

[[redirects]]
from = "/agenda/archives/index.html"
to = "/evenements/archives/"

[[redirects]]
from = "/lassociation/membres/equipe-editoriale/index.html"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/agenda/2024/07/index.html"
to = "/evenements/2024/07/"

[[redirects]]
from = "/publications/ecologie/index.html"
to = "/publications/thematique/ecologie/"

[[redirects]]
from = "/archives-expositions/index.html"
to = "/expositions/archives-expositions/"

[[redirects]]
from = "/publications/thematiques/index.html"
to = "/publications/thematique/"

[[redirects]]
from = "/agenda/2024/01/index.html"
to = "/evenements/2024/01/"

[[redirects]]
from = "/lassociation/index.html"
to = "/a-propos/"

[[redirects]]
from = "/agenda/2024/09/index.html"
to = "/evenements/2024/09/"

[[redirects]]
from = "/actualites/2024-08-15-discours-de-thomas-thibault/index.html"
to = "/publications/2024-08-15-discours-de-thomas-thibault/"

[[redirects]]
from = "/agenda/index.html"
to = "/evenements/"

[[redirects]]
from = "/lassociation/membres/index.html"
to = "/personnes/"

[[redirects]]
from = "/actualites/index.html"
to = "/publications/"

[[redirects]]
from = "/agenda/2024/index.html"
to = "/evenements/2024/"

[[redirects]]
from = "/agenda/2024/11/index.html"
to = "/evenements/2024/11/"

[[redirects]]
from = "/lassociation/raison-detre/index.html"
to = "/a-propos/manifeste/"

[[redirects]]
from = "/agenda/2024/03/index.html"
to = "/evenements/2024/03/"

[[redirects]]
from = "/actualites/2024-08-15-dematerialisation/index.html"
to = "/publications/2024-08-15-dematerialisation/"

